apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/operator-type: non-standalone
  name: orc.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Image is the Schema for an ORC resource.
      displayName: Image
      kind: Image
      name: images.openstack.k-orc.cloud
      version: v1alpha1
  description: Openstack Resource Controller, or ORC, is a Kubernetes API for declarative
    management of OpenStack resources. By fully controlling the order of OpenStack
    operations, it allows consumers to easily create, manage, and reproduce complex
    deployments. ORC aims to be easily consumed both directly by users, and by higher
    level controllers.
  displayName: ORC operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Infrastructure
  links:
  - name: Homepage
    url: https://k-orc.cloud
  - name: Source code
    url: https://github.com/k-orc/openstack-resource-controller
  maturity: alpha
  minKubeVersion: 1.29.0
  provider:
    name: The ORC Authors
    url: https://k-orc.cloud
  version: 0.0.1
