---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Volume
    size: 100
    volumeTypeRef: my-volume-type
    metadata:
      key1: value1
      key2: value2
