---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  cloudCredentialsRef:
    # TODO(scaffolding): Use openstack-admin if the resouce needs admin credentials to be created
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Volume
    # TODO(scaffolding): Add all fields the resource supports
