on:
  push:
    branches:
    - main
  merge_group:
  pull_request:
name: generate
permissions:
  contents: read

jobs:
  make-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: |
          make generate
          git diff --exit-code
