on:
  push:
    branches:
    - main
    paths:
    - 'website/**'
    - 'api/v1alpha1/**'
    - '.github/workflows/website.yaml'
name: website

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Pip install
      run: pip install -Ur website/requirements.txt

    - name: Build the site
      run: mkdocs build --verbose --strict --config-file website/mkdocs.yml --site-dir rendered

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: k-orc
        directory: website/rendered
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
